import numpy as np

from gs_experiment.camera import translate_camera, translate_cameras, turntable_ring
from gs_experiment.scene_spec import differentiation_scene, quick_validation_scene


def test_translate_camera_preserves_orientation_shifts_center():
    cam = turntable_ring(radius=5.0, n_views=1)[0]
    offset = np.array([3.0, -1.0, 2.0])

    moved = translate_camera(cam, offset)

    np.testing.assert_allclose(moved.center, cam.center + offset)
    np.testing.assert_allclose(moved.forward, cam.forward)
    np.testing.assert_allclose(moved.up, cam.up)


def test_translate_camera_look_at_target_shifts_by_same_offset():
    # a camera generated by turntable_ring looks at the origin; after
    # translating by `offset`, it should look at `offset` instead, since
    # forward/up are direction vectors unaffected by translation.
    cam = turntable_ring(radius=5.0, n_views=1)[0]
    offset = np.array([10.0, 0.0, 0.0])
    moved = translate_camera(cam, offset)

    # distance from moved camera to the shifted target, along `forward`,
    # should match the original camera's distance to the origin
    original_dist_to_target = np.linalg.norm(cam.center - np.zeros(3))
    to_target = offset - moved.center
    assert np.dot(to_target / np.linalg.norm(to_target), moved.forward) > 0.999
    np.testing.assert_allclose(np.linalg.norm(to_target), original_dist_to_target, atol=1e-8)


def test_translate_cameras_applies_to_every_camera():
    cams = turntable_ring(radius=5.0, n_views=4)
    offset = np.array([1.0, 2.0, 3.0])
    moved = translate_cameras(cams, offset)
    for c, m in zip(cams, moved):
        np.testing.assert_allclose(m.center, c.center + offset)


def test_quick_validation_scene_has_objects_and_cameras():
    spec = quick_validation_scene(n_views=8)
    assert len(spec.objects) > 0
    assert len(spec.cameras) == 8
    payload = spec.to_json_dict()
    assert "objects" in payload and "cameras" in payload


def test_differentiation_scene_separates_wide_and_narrow_rigs_by_geometry():
    spec = differentiation_scene(n_ring_views=6, n_arc_views=4, separation=18.0)

    ring_cameras = spec.cameras[:6]
    arc_cameras = spec.cameras[6:]

    # ring cameras orbit near the origin; arc cameras orbit near the
    # translated narrow-cluster center -- this is what makes real frustum
    # attribution (not fiat) separate the two zones later.
    ring_dists_to_origin = [np.linalg.norm(c.center) for c in ring_cameras]
    arc_dists_to_origin = [np.linalg.norm(c.center) for c in arc_cameras]
    assert max(ring_dists_to_origin) < 10.0
    assert min(arc_dists_to_origin) > 10.0

    # object clusters are correspondingly separated
    locations = np.array([o.location for o in spec.objects])
    assert locations[:, 0].min() < 2.0  # wide cluster near x=0
    assert locations[:, 0].max() > 15.0  # narrow cluster near x=separation
